title:             Laniakea
email:             your-email@example.com
description:       Automatic deployment of virtual Galaxy environments for life science
author:            Start Bootstrap
baseurl:           "/elixir-italy-laniakea"
url:               "http://mtangaro.github.io"

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'News', link: '/posts'}
  - {name: 'Documentation', link: 'https://laniakea.readthedocs.io/en/latest/'}
  - {name: 'Deploy', link: 'https://cloud-90-147-75-117.cloud.ba.infn.it/login'}
  - {name: 'Cite', link: '/about'}
  - {name: 'Contact', link: '/contact'}

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
